source 'https://rubygems.org'

gem 'async-io'
gem 'falcon'
gem 'sinatra'
gem 'sinatra-reloader'
gem 'slim'
gem 'sass'

# gem 'rack', '~> 2.2.8'
# gem 'rackup', '~> 2.1'
gem 'rack'
gem 'rackup'
gem 'sequel'
gem 'sequel_pg'

# gem 'opentelemetry-sdk'
# gem 'opentelemetry-exporter-otlp'
# gem 'opentelemetry-instrumentation-all'

gem 'stack-service-base'
gem 'rubyzip'

group :development do
  gem 'rubocop'
end